# -*- coding: utf-8 -*-
"""strategy 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLYEeon1enW4yNqnAKFRNWfPt-2BceWf
"""

pip install fastapi uvicorn

#Preload the Model on API Startup, Modify the script to load the model when the API starts instead of on every request.
#This ensures that the model is in memory before any request comes in.

@api.on_event("startup")
def load_model_on_startup():
    model_handler.load_model()

#Remove Unnecessary File I/O
#Modify the Predict method to assume the model is always loaded

def Predict(self, input_data: np.ndarray):
    if self.model is None:
        raise HTTPException(status_code=500, detail="Model not loaded")
    return self.model.predict(input_data)

#Use a More Efficient Model Storage Method

#Instead of using pickle, consider joblib, which is optimized for storing and loading large NumPy arrays.

import joblib
def save_model(self):
    joblib.dump(self.model, 'model.pkl')

def load_model(self):
    self.model = joblib.load('model.pkl')

