# -*- coding: utf-8 -*-
"""strategy 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLYEeon1enW4yNqnAKFRNWfPt-2BceWf
"""

pip install fastapi uvicorn

from fastapi import FastAPI

app = FastAPI()
predictor = None  # Global instance

# --- Preload Model at Startup ---
@app.on_event("startup")
def load_model():
    global predictor
    predictor = ModelPredictor("model_v1.pkl")  # Initialize once

# --- Endpoint ---
@app.post("/predict")
async def predict_endpoint(data: dict):
    processed_data = predictor.preprocess(data)
    return {"prediction": predictor.predict(processed_data)}